[package]
name = "binclock-rs"
version = "0.1.0"
authors = ["Anisse Astier <anisse@astier.eu>"]
edition = "2018"

[dependencies]
chrono = "0.4.11"

[dependencies.sdl2]
version = "0.34.1"
default-features = false
features = []
